/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KeyAuthorizationForm.java
 *
 * Created on Dec 10, 2010, 5:08:08 AM
 */
package com.heidi.keymanager;

/**
 *
 * @author mujahid
 */
import com.heidi.services.KeyAuthorization;



public class KeyAuthorizationForm extends javax.swing.JFrame {

   
    KeyConfig keyConfig;

    /** Creates new form KeyAuthorizationForm */
    public KeyAuthorizationForm() {
        initComponents();
        String[] tmp = new String[0];

       
        keyConfig= new KeyConfig();
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOK = new javax.swing.JButton();
        txtOwner = new javax.swing.JTextField();
        txtOwnerEmail = new javax.swing.JTextField();
        txtMobileNumber = new javax.swing.JTextField();
        txtKey = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("hPOS Key Manager");
        setName("jKeyFrame"); // NOI18N

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Email");

        jLabel3.setText("Mobile");

        jLabel4.setText("Key");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOwnerEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOwner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                            .addComponent(txtKey, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMobileNumber, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOwnerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnClose))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnOK.getAccessibleContext().setAccessibleName("btnOK");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:

        String ownerName = this.txtOwner.getText();
        String ownerEmail = this.txtOwnerEmail.getText();
        String ownerMobile = this.txtMobileNumber.getText();
        String posKey = this.txtKey.getText();

        if (ownerName == null || ownerName.length() == 0) {
        }

        if (ownerName.length() != 0 && ownerEmail.length() != 0
                && ownerMobile.length() != 0 && posKey.length() != 0) {

            KeyAuthorization keyAuthorization = new KeyAuthorization();

            try {
                boolean keyStatus = keyAuthorization.getKeyStatus(ownerName, ownerEmail, ownerMobile, posKey);
                if (keyStatus) {
                    
                    String writableLocalKey = keyAuthorization.writableWindowsLocalKey(posKey);
                    String writableKey = keyAuthorization.getEncryptedLicenseKey(posKey);

                    
                    //configFile.setProperty(posKey, posKey);




                    keyConfig.setProperty("machine.local", writableLocalKey);
                    keyConfig.setProperty("machine.install", writableKey);

                    

                    keyConfig.save();
                    javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null, "Key activated. Restart HEIDI POS.", "Key Activation",
                            javax.swing.JOptionPane.DEFAULT_OPTION);

//                    javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null, writableLocalKey, "writableLocalKey",
//                            javax.swing.JOptionPane.DEFAULT_OPTION);
//
//                    javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null, writableKey, "writableKey",
//                            javax.swing.JOptionPane.DEFAULT_OPTION);

                    System.exit(0);
                } else {
                    javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null, "Key activation failed", "Key Activation",
                            javax.swing.JOptionPane.DEFAULT_OPTION);
                }
            } catch (Exception ex) {
                 javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null, ex.getMessage(), "Key Activation Error",
                            javax.swing.JOptionPane.DEFAULT_OPTION);
            }
        } else {
            javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null, "Some inputs are missing", "Key Activation",
                            javax.swing.JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new KeyAuthorizationForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtOwner;
    private javax.swing.JTextField txtOwnerEmail;
    // End of variables declaration//GEN-END:variables
}
